minor cleanup and adjustments
younix/lchat pull request #12
Opened 2022-10-07 12:19 UTC by tosch42

In addition to what we've discussed via mail, I also changed `CC` to c99 (which is the default value, but I think keeping the assignment is convenient, so the user can just change the value instead of adding a whole new line).
Since libgrapheme 2.0.0 was released yesterday, I changed `grapheme_next_character_break` to `grapheme_next_character_break_utf8`

2022-10-07 12:56 UTC, younix requested changes

2022-10-07 12:56 UTC, younix commented on slackline.c
> +		byte += grapheme_next_character_break_utf8(ptr+byte, sl->blen-byte);
please don't do this here.
a libgrapheme update have to be done in a separate change.

2022-10-07 12:56 UTC, younix commented on config.mk
> -CFLAGS = -std=c99 -pedantic -Wall -Wextra -g
why do you delete -std=c99 here?

2022-10-07 12:56 UTC, younix commented on config.mk
> +CC = c99
the whole line should be removed

2022-10-07 13:27 UTC, tosch42 commented on config.mk
> -CFLAGS = -std=c99 -pedantic -Wall -Wextra -g
POSIX states[1] that `CC`'s default value should be `c99` (or a utility with similar effects). Keeping `-std` would be redundant. But if you like it the other way around, that's fine.

[1] https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html#tag_20_76_13_09

2022-10-08 00:06 UTC, younix commented on config.mk
> -CFLAGS = -std=c99 -pedantic -Wall -Wextra -g
This is for implementations of make(1) and not for authors of Makefiles.
Why do we need to set  CC to the default value anyway?
Thus, just delete the assignment of CC.

btw: I would get **/bin/sh: c99: not found** with this.

2022-10-08 10:18 UTC, tosch42 commented on config.mk
> -CFLAGS = -std=c99 -pedantic -Wall -Wextra -g
Alright, I'd open another pull request so the commit history is less cluttered. Thanks!

2022-10-08 10:19 UTC, closed without merging